import { sql } from 'drizzle-orm'
import { index, jsonb, numeric, primaryKey, snakeCase, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core'

/**
 * Hypertable. The CREATE TABLE is generated by drizzle-kit from this definition;
 * `create_hypertable`, the customer/time index and compression live in the hand-written
 * migration `drizzle/*_usage_events_hypertable` (drizzle-kit generate --custom).
 *
 * No FK to customers on purpose: event tables should not block customer deletion
 * and TimescaleDB performs best without cross-table constraints on hypertables.
 */
export const usageEvents = snakeCase.table(
  'usage_events',
  {
    id: uuid().notNull().default(sql`uuidv7()`),
    occurredAt: timestamp({ withTimezone: true }).notNull(),
    customerId: uuid().notNull(),
    eventName: text().notNull(),
    quantity: numeric({ precision: 18, scale: 6 }).notNull().default('1'),
    /** Producer-owned id: dedup key here and `external_id` when forwarded to Polar */
    eventId: text().notNull(),
    metadata: jsonb().$type<Record<string, string | number | boolean>>().notNull().default({}),
    receivedAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
    /** Set once the event has been ingested into Polar */
    polarSyncedAt: timestamp({ withTimezone: true }),
  },
  (t) => [
    primaryKey({ columns: [t.occurredAt, t.id] }),
    index('usage_events_event_id_idx').on(t.eventId),
    // hypertable unique indexes must include the partition column; eventId-only uniqueness
    // is enforced by the repository pre-check
    uniqueIndex('usage_events_event_id_occurred_at_key').on(t.eventId, t.occurredAt),
  ],
)
